service: AppEngineTest
runtime: python311
instance_class: F1

automatic_scaling:
  max_concurrent_requests: 80
  target_throughput_utilization: 0.95
  target_cpu_utilization: 0.75
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: 1.7s
  max_pending_latency: 14.6s

entrypoint: gunicorn -b :8080 -w 2 main:app
